name: ✅ testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install packages
        run: npm install
        
      - name: start testing
        run: npm run test
      
