name: ✅ testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Testing
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '16'
      - run: npm install
      - run: npm jest --silent --verbose --env=jsdom
